### ISSUE TITLE
Connector: Error: State "mqtt.0.Awtrix.basics" not found

### ISSUE THREAD

**Issue by Hopsen** [Pittini/iobroker-awtrix#1]
Hi Pittini,

erstmal danke für die Arbeit. Ich habe gestern die beiden Sktipte erstellt.

Ich erhalte allerdings keine Werte von der Awtrix. Der Connector spuckt einen Error aus. Habe mich an die Anleitung gehalten.
Die Verbindung zu mqtt ist eingerichtet und die Awtrix schickt unter matt.0 auch die aktuelle App usw.

<img width="1104" alt="Bildschirmfoto 2021-07-21 um 21 54 04" src="https://user-images.githubusercontent.com/17110420/126552443-ff78a058-2896-4b83-88b3-94385a1daa9c.png">

Hast du einen Tipp für mich?

**Comment by Pittini** [comment]
Naja, steht ja da, das Problem. Gugg doch mal ob der Datenpunkt existiert?

**Comment by Hopsen** [comment]
Der Datenpunkt existiert nicht. 
Unter mqtt kommen vier Informationen rein. Daher scheint die Anbindung der Awtrix an mqtt grundsätzlich doch zu funktionieren.

<img width="1312" alt="Bildschirmfoto 2021-07-22 um 09 58 26" src="https://user-images.githubusercontent.com/17110420/126606852-c6f961ce-f21d-4836-bf1c-462780b83e1d.png">

**Comment by Pittini** [comment]
Nich wirklich, da fehlt ne Menge, siehe Bild. Notfalls mal manuell anlegen. Solange die nich da sind wird das Skript maulen, zurecht.

![2021-07-22 11_44_57-objects - Iobroker](https://user-images.githubusercontent.com/51408942/126620072-8e5c7049-7e69-452e-b362-27c1d745d8e9.png)

**Comment by Hopsen** [comment]
Hi,

habe meinen mqtt broker gewechselt und jetzt klappt es. Es klappt zwar zu Publisher über mqtt explorer, aber von der Awtrix kam nix an.
Jetzt läuft der broker über iobroker und alle Werte werden angezeigt.

Danke dir für die Arbeit.
