### ISSUE TITLE
GELÖST: Läuft nicht durch ... keine Einträge unter Javascript nur Ordner

### ISSUE THREAD

**Issue by RoboCop0815** [Pittini/iobroker-awtrix#2]
<html><body>
<div class="splitter-layout iob3 iob7"><div class="layout-pane layout-pane-primary"><div class="iob5 iobVerticalSplitter"><div class="splitter-layout splitter-layout-vertical"><div class="layout-pane" style="height: 150px;"><div class="iob60"><div class="iob61" style="">

11:20:26.474 | info | javascript.0  (115561) script.js.Scripte.AWTRIX_Connector: Response triggered  dp.state.val={"success":false,"exeption":"Matrix is not connected.  AWTRIX does not running"}
-- | -- | --
11:20:26.502 | info | javascript.0  (115561) script.js.Scripte.AWTRIX_Connector: Response triggered  dp.state.val={"success":false,"exeption":"Matrix is not connected.  AWTRIX does not running"}
11:21:17.328 | info | javascript.0 (115561) script.js.Scripte.AWTRIX_Connector: Response triggered dp.state.val=Hello from AWTRIX
11:22:46.543 | info | javascript.0 (115561) script.js.Scripte.AWTRIX_Connector: Response triggered dp.state.val=Hello from AWTRIX
11:24:26.620 | info | javascript.0  (115561) script.js.Scripte.AWTRIX_Connector: Response triggered  dp.state.val={"success":false,"exeption":"Matrix is not connected.  AWTRIX does not running"}
11:24:26.664 | info | javascript.0  (115561) script.js.Scripte.AWTRIX_Connector: Response triggered  dp.state.val={"success":false,"exeption":"Matrix is not connected.  AWTRIX does not running"}
11:25:19.323 | info | javascript.0 (115561) script.js.Scripte.AWTRIX_Connector: Response triggered dp.state.val=Hello from AWTRIX
11:26:46.727 | info | javascript.0 (115561) script.js.Scripte.AWTRIX_Connector: Response triggered dp.state.val=Hello from AWTRIX
11:28:26.664 | info | javascript.0  (115561) script.js.Scripte.AWTRIX_Connector: Response triggered  dp.state.val={"success":false,"exeption":"Matrix is not connected.  AWTRIX does not running"}
11:28:26.700 | info | javascript.0  (115561) script.js.Scripte.AWTRIX_Connector: Response triggered  dp.state.val={"success":false,"exeption":"Matrix is not connected.  AWTRIX does not running"}

<div style="float: left; clear: both;"></div></div></div></div></div></div></div></div>
</body>
</html>
unter MQTT
![mqtt](https://user-images.githubusercontent.com/42671266/188852386-d1cce73d-2709-4761-8d2a-477e24e2e843.png)

**Comment by Pittini** [comment]
"Matrix is not connected. AWTRIX does not running" sagt doch eigentlich schon alles. Das Skript setzt schon ne funktionierende Einbindung der Awtrix via mqtt voraus. Solang das nicht 1a klappt, kann auch das Skript nicht funktioneren.

**Comment by RoboCop0815** [comment]
![mqtt](https://user-images.githubusercontent.com/42671266/188881541-403b279b-e4b1-4424-871f-68df9b036bd6.png)
Wo finde ich den Fehler wenn ich under MQTT die Meldung über Online Verbindung habe...

oder kann das mit dem MQTT Port (1886) zutun haben?

**Comment by Pittini** [comment]
Woher soll ich denn wissen welchen Port Du für mqtt verwendest? Auf jeden Fall fehlt da etliches, sieht so aus wenns passt:
![2022-09-08 01_59_27-objects - Iobroker](https://user-images.githubusercontent.com/51408942/189005309-71d60110-416d-4bb2-b2cd-28e9b4749bc6.png)

**Comment by RoboCop0815** [comment]
Moin, hatte nur einen Ausschnitt gelinkt, sieht bei mir auch so aus...
GELÖST: Script gestoppt - AWTRIX Einträge unter Javascript gelöscht und Script wieder gestartet.
Jetzt ist alles da.
