### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by Quacoo** [Pittini/iobroker-awtrix#3]
I am using your controller and connector script permanently, thanks a lot for the great work.

I would like to suggest an enhancement to show a few more info's unless not set. 

I would like to show:
climate:

home:
inside outside temperature and relative humidity (done)
cellar temperature and relative humidity
Garage temperature and relative humidity
Pool temperature, redox and PH

second region (holiday home):
inside outside temperature and relative humidity
cellar temperature and relative humidity
Garage temperature and relative humidity
Pool temperature, redox and PH

alarms:
letter box
ventilation cellar
ventilation garage
ventilation rooms

Thank you

Best regards

**Comment by Pittini** [comment]
Sorry for late response. I will not enhance the script, but it is written so enhancements are relatively easy to implement by everybody who has basic JS skills. Additionally I think what you wish is too much  and can not really be recoknized while scrolling thru the Awtrrix.
